---
services:
  spotlight.en:
    image: dbpedia/dbpedia-spotlight
    container_name: dbpedia-spotlight.en
    restart: unless-stopped
    ports:
      - "0.0.0.0:2222:80"
    command: /bin/spotlight.sh en
volumes:
  spotlight-model: {}
